version: "3.9"

services:

  inventory-service:
    build:
      context: ./inventory-service
    container_name: inventory-service
    ports:
      - "5002:5000"

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "5001:5000"