# Key unik project di SonarQube
sonar.projectKey=technnova-devops

# Nama display project
sonar.projectName=technova-devops

# Source code lokasi mana yang mau di-scan (misal folder src atau root '.')
sonar.sources=.

# Encoding
sonar.sourceEncoding=UTF-8
