# Key unik project di SonarQube
sonar.projectKey=technova-devops

# Nama display project
sonar.projectName=technova-devops

# Source code lokasi mana yang mau di-scan
sonar.sources=.

# Encoding
sonar.sourceEncoding=UTF-8
