name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature-monitoring
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Repository
        run: |
          echo "Repository berhasil di-checkout."
          ls -la

      - name: Pipeline Success
        run: echo "CI/CD berhasil dijalankan."
